"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import AuthProvider from '@/shared/providers/AuthProvider'
import { AuthenticationResult, EventMessage, EventType } from "@azure/msal-browser";
import { msalInstance } from '@/shared/configurations/authConfig';

const inter = Inter({ subsets: ['latin'] });

localStorage.theme = 'light'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Always keep this function in layout
const accounts = msalInstance.getAllAccounts();
if (accounts.length > 0) {
  msalInstance.setActiveAccount(accounts[0]);
};

// Always keep this function in layout
msalInstance.addEventCallback((event: EventMessage) => {
  if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
    const payload = event.payload as AuthenticationResult;
    const account = payload.account;
    if (account) {
      msalInstance.setActiveAccount(account);
    }
  }
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
